---
title: "PROJECT TITLE"
author: "Kimchi Stew"
date: "4/23/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Packages & Data

```{r load-packages-data}
library(stringr)
library(tidyverse)
library(broom)

business <- read_csv("yelp-dataset-csv/yelp_business.csv")
business_attr <- read_csv("yelp-dataset-csv/yelp_business_attributes.csv")
business_hours <- read_csv("yelp-dataset-csv/yelp_business_hours.csv")
yelp_review <- read_csv("yelp-dataset-csv/yelp_review.csv", n_max = 10000)
food <- business %>% 
  filter(str_detect(categories, "Food|Restaurants"))
food_ids <- food %>% 
  select(business_id) %>% 
  pull()
food_attr <- business_attr %>% 
  filter(business_id %in% food_ids)
```

### Miles


```{r}
#join with attributes
# business %>%
#   inner_join(business_attr, by = "business_id")

food_attr <- food_attr %>% 
  select(-starts_with("Hair"))

food_attr_temp <- food_attr %>% 
  select(-business_id)

food_attr_temp[food_attr_temp == "Na"] <- 0
#food_attr_temp[food_attr_temp != 0] <- 1

test <- food_attr_temp %>% 
  summarise_all(funs(sum(. == "True"))) %>% 
  gather(attribute, true, 1:ncol(.))

food_attr_temp %>% 
  summarise_all(funs(sum(. == "False"))) %>% 
  gather(attribute, false, 1:ncol(.)) %>% 
  inner_join(test, by = "attribute") %>% 
  mutate(total = false + true,
         perc_true = round(true / (false + true),2)) %>% 
  filter(total > 20, true > 20) %>% 
  arrange(desc(total))



```

```{r}



# ratings by alcohol & good for kids
food_attr %>%
  select(Alcohol, GoodForKids, business_id) %>% 
  filter(!is.na(Alcohol), !is.na(GoodForKids)) %>%
  inner_join(food, by = "business_id") %>% 
  group_by(GoodForKids, Alcohol) %>%
  summarise(mean = mean(stars),
            n = n())

# get top # cities
food %>% 
  count(city) %>% 
  arrange(desc(n))

# filter for toronto, non null neighborhoods
toronto_neighborhood <- food %>% 
  filter(city == "Toronto", neighborhood != "")

# look at top neighborhoods
toronto_neighborhood %>%
  count(neighborhood) %>% 
  arrange(desc(n))

# aggregate postal codes (heirarchical structure so just took two few numbers)
toronto_neighborhood <- toronto_neighborhood %>%
  mutate(postal_code_short = substr(postal_code, 1 , 2))

# summary stats by neighborhood
toronto_neighborhood %>% 
  group_by(neighborhood) %>% 
  summarise(mean = mean(stars), n = n()) %>% 
  filter(n > 10) %>% 
  arrange(desc(mean))

# kmeans by attributes 7 through 10
kmns <- kmeans(toronto_neighborhood[8:11], 10)

# view kmeans results
head(augment(kmns, toronto_neighborhood))
tidy(kmns)

# view postal codes in space
ggplot(toronto_neighborhood, aes(x = latitude, y = longitude, color = postal_code_short)) +
  geom_point()

```


```{r}
# kmeans exploratory analysis
kmns <- data.frame(k=1:9) %>% 
  group_by(k) %>% 
  do(kmns=kmeans(toronto_neighborhood[8:9], .$k))

clusters <- kmns %>%
    group_by(k) %>%
    do(tidy(.$kmns[[1]]))

assignments <- kmns %>%
    group_by(k) %>%
    do(augment(.$kmns[[1]], toronto_neighborhood))

clusterings <- kmns %>%
    group_by(k) %>%
    do(glance(.$kmns[[1]]))

p1 <- ggplot(assignments, aes(latitude, longitude)) +
    geom_point(aes(color=.cluster)) +
    facet_wrap(~ k)

p1
```
### Katie

```{r}

```


### Ivy

```{r}

```




